/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *   META_msg.h
 *
 * Project:
 * --------
 *   Maui META APP
 *
 * Description:
 * ------------
 *  META message header
 *
 * Author:
 * -------
 *  Andy Ueng (mtk00490)
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision:   1.11  $
 * $Modtime:   Oct 25 2005 11:19:34  $
 * $Log:   //mtkvs01/vmdata/meta_app/archives/MauiMETA/factory/meta_msg.h-arc  $
 *
 * Apr 24 2008 mtk00490
 * [STP100001693] [META] META ver 5.0816.0
 *
 *
 * Feb 22 2008 mtk00490
 * [STP100001646] [META] META ver 5.0808.0
 *
 *
 * Dec 3 2007 mtk00490
 * [STP100001570] [META] META ver 5.0748.0
 *
 *
 * Sep 8 2007 mtk00490
 * [STP100001505] [META] META ver 5.6.0
 *
 *
 * May 19 2007 mtk00490
 * [STP100001406] [META] META ver 5.3.8
 *
 *
 * Feb 8 2007 mtk00490
 * [STP100001308] [META] META ver 5.3.6.0
 *
 *
 * Nov 23 2006 mtk00490
 * [STP100001231] [META] META ver 5.3.4.0
 *
 *
 * Oct 15 2006 mtk00490
 * [STP100001171] [META] META ver 5.3.1.0
 *
 *
 * Jul 18 2006 mtk00490
 * [STP100001005] [META]META ver 3.7.05
 *
 *
 * Mar 16 2006 mtk00490
 * re-import flash_tool, meta_app, meta_dll, MCUProfiling  into VOB
 *
 *
 *    Rev 1.11   Oct 25 2005 14:13:34   mtk00490
 * IP2 calibration support Skyworks 74117, 74400
 *
 *    Rev 1.10   Sep 04 2005 11:02:06   mtk00490
 * 1. ADC calibration support Keithley 2306, Agilent E3631A power supply
 * 2. APC calibration support Skyworks 77328
 * 3. APC calibration support two APC DC offset
 * 4. APC ramp profile runtime setting
 * 5. Graphic APC ramp profile runtime setting
 * 6. Acoustic FIR tuning support Acqua file format
 *
 *    Rev 1.9   Apr 18 2005 15:47:32   mtk00490
 * crystal AFC calibration fine tune
 *
 *    Rev 1.8   Jan 30 2005 17:54:32   mtk00490
 * Audio
 * 1. Apply microphone, sidetone editor value to all element of array
 * 2. resolve number of element in frequency array = 2 * number of element of weight array
 *
 *    Rev 1.7   Jan 10 2005 11:10:32   mtk00490
 * 1. Automatic BB chip and external clock rate detection
 * 2. Support baud rate 57600 (for FPGA test)
 * 3. RF tool
 * a.Trim IQ, offset IQ sweep (get phase error, original offset, IQ imbalance information from equipment)
 * 4. Audio
 * a.Acoustic FIR tuning and melody FIR tuning integrate with AFTDLL.dll (provide freqz and firls function, user does not to install MATLAB for FIR tuning)
 * 5. Update parameter
 * a.add barcode and IMEI read/write
 * 6. Factory
 * a.support DCS, PCS, GSM850 AFC calibration
 * b.phase error calibration
 * c.user configurable current limit
 * d.add APC DAC to result file
 * e.add AFC_BAND, AFC_ARFCN to TCVCXO AFC CFG editor
 * f.add CURRENT_LIMIT to ADC CFG editor
 * g.add phase error CFG editor
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

//---------------------------------------------------------------------------


#ifndef _META_MSG_H_
#define _META_MSG_H_

#include <windows.h>
//------------------------------------------------------------------------------
typedef  enum
{
    WM_META_MSG_START = WM_USER+100,

    // messages for FDM read and write
    WM_FDM_READ_REC_CNF = WM_META_MSG_START,
    WM_FDM_WRITE_REC_CNF,

    // messages for RF calibration
    WM_RF_PM_CNF,
    WM_RF_CONT_RX_CNF,
    WM_RF_CONT_TX_CNF,
    WM_RF_TX_LEVEL_CNF,
    WM_RF_AFC_CONTROL_CNF,

    // messages for RF table in FDM read and write
    WM_RF_PATH_LOSS_READ_CNF,
    WM_RF_PATH_LOSS_WRITE_CNF,
    WM_RF_LEVEL_RAMP_READ_CNF,
    WM_RF_LEVEL_RAMP_WRITE_CNF,
    WM_RF_AFC_READ_CNF,
    WM_RF_AFC_WRITE_CNF,

    // messages for l1sp and midi
    WM_L1SP_HEADSET_IND,
    WM_MIDI_DOWNLOAD,
    WM_MIDI_PLAY_CNF,
    WM_MIDI_PLAY_OVER,
    WM_MIDI_DEL,
    WM_MIDI_INFO,
    WM_MIDI_PLAY_FAIL,

    // messages for voice memo
    WM_VM_INFO,
    WM_VM_PLAY_CNF,
    WM_VM_PLAY_OVER,
    WM_VM_DEL,
    WM_VM_REC,
    WM_VM_REC_FULL,
    WM_VM_TAG,

    // messages for acoustic fir-coefficient
    WM_FIR_READ_CNF,
    WM_FIR_WRITE_CNF,

    // messages corresponding error from META DLL
    WM_META_DLL_ERROR_FRAME_ERROR,
    WM_META_DLL_ERROR_NO_CALLBACK,
    WM_META_DLL_ERROR_PRIMITIVE_ERROR,

    // messages corresponding to META DLL return values
    WM_META_DLL_SUCCESS,
    WM_META_DLL_FAILED,
    WM_META_DLL_COMM_FAIL,
    WM_META_DLL_NORESPONSE,
    WM_META_DLL_BUFFER_LEN,
    WM_META_DLL_GROUP_INVALID,
    WM_META_DLL_ELEMENT_INVALID,
    WM_META_DLL_FIELD_INVALID,
    WM_META_DLL_VALUE_LEN,
    WM_META_DLL_VM_NOENTRY,
    WM_META_DLL_VM_BUFFERFULL,
    WM_META_DLL_VM_BADENTRY,
    WM_META_DLL_VM_FAIL,
    WM_META_DLL_FILE_BAD,
    WM_META_DLL_PARAM_INVALID,
    // new added
    WM_META_DLL_INTERNAL_DB_ERR,
    WM_META_DLL_NO_MEMORY,
    WM_META_DLL_INVALID_ARGUMENTS,
    WM_META_DLL_TIMEOUT,
    WM_META_DLL_BUSY,

    //--------------------------------
    WM_META_DLL_ERROR_UNDEFINE_ERROR,

    // equipement dll
    WM_LOAD_AGE1960_DLL_FAILED,
    WM_LOAD_AGE1960_DLL_FUNCTION_FAILED,
    WM_FREE_AGE1960_DLL_FAILED,
    WM_LOAD_HP663X2_DLL_FAILED,
    WM_LOAD_HP663X2_DLL_FUNCTION_FAILED,
    WM_FREE_HP663X2_DLL_FAILED,
    WM_LOAD_HP661X_DLL_FAILED,
    WM_LOAD_HP661X_DLL_FUNCTION_FAILED,
    WM_FREE_HP661X_DLL_FAILED,
    WM_LOAD_HPE3631A_DLL_FAILED,
    WM_LOAD_HPE3631A_DLL_FUNCTION_FAILED,
    WM_FREE_HPE3631A_DLL_FAILED,
    WM_LOAD_VISA32_DLL_FAILED,
    WM_LOAD_VISA32_DLL_FUNCTION_FAILED,
    WM_FREE_VISA32_DLL_FAILED,
    WM_LOAD_N4010A_DLL_FAILED,
    WM_LOAD_N4010A_DLL_FUNCTION_FAILED,
    WM_FREE_N4010A_DLL_FAILED,
    WM_LOAD_CONTROLS_DLL_FAILED,
    WM_LOAD_CONTROLS_DLL_FUNCTION_FAILED,
    WM_FREE_CONTROLS_DLL_FAILED,
//         WM_LOAD_MFILES_DLL_FAILED,
//         WM_LOAD_MFILES_DLL_FUNCTION_FAILED,
//         WM_FREE_MFILES_DLL_FAILED,
    //--------------------------------
    // message for Equipment
    // vi
    WM_VI_INVALID_SESSION_HANDLE,

    // agilent 8960
    WM_MF_AGE8960_SET_APPLICATION_FORMAT_FAIL,
    WM_MF_AGE8960_SET_OPERATION_MODE_FAIL,
    WM_MF_RCT_SET_CABLE_LOSS_FAIL,
    WM_MF_AGE8960_INIT_FAIL,
    WM_MF_AGE8960_DCL_FAIL,
    WM_MF_AGE8960_RESET_FAIL,
    WM_MF_AGE8960_SET_BAND_FAIL,
    WM_MF_AGE8960_SET_TRAN_CONT_FAIL,
    WM_MF_AGE8960_SET_TRAN_BURST_FAIL,
    WM_MF_RCT_SET_BCH_ARFCN_FAIL,
    WM_MF_AGE8960_SET_RF_GENERATOR_FAIL,       // cmu
    WM_MF_AGE8960_SET_BURST_TRANSMIT_FAIL,    // cmu
    WM_MF_AGE8960_SET_GENERATOR_TSC_FAIL,     // cmu
    WM_MF_AGE8960_SET_BIT_MODULATION_FAIL,    // cmu
    WM_MF_AGE8960_SET_POWER_FAIL,
    WM_MF_RCT_SET_TSC_FAIL,
    WM_MF_AGE8960_SET_CODING_SCHEME_FAIL,
    WM_MF_AGE8960_SET_TCH_ARFCN_FAIL,
    WM_MF_RCT_SET_PDTCH_ARFCN_FAIL,
    WM_MF_AGE8960_SET_TCH_TIMESLOT_FAIL,
    WM_MF_AGE8960_SET_MESA_FUNC_PFER_FAIL,
    WM_MF_AGE8960_READ_PFER_FAIL,
    WM_MF_AGE8960_SET_MESA_FUNC_TX_POWER_FAIL,
    WM_MF_AGE8960_SET_MS_TX_LEVEL_FAIL,
    WM_MF_AGE8960_SET_TX_POWER_CONT_ON_FAIL,
    WM_MF_AGE8960_SET_TX_POWER_CONT_OFF_FAIL,
    WM_MF_RCT_READ_TX_POWER_FAIL,
    WM_MF_RCT_SET_PVT_FAIL,
    WM_MF_RCT_READ_PVT_FAIL,
    WM_MF_AGE8960_WAIT_FOR_INIT_DONE_Q_FAIL,
    WM_MF_AGE8960_SET_MESA_FUNC_IQ_TUNNING_FAIL,
    WM_MF_AGE8960_READ_IQ_TUNNING_FAIL,
    WM_MF_AGE8960_CLOSE_FAIL,
    WM_MF_AGE8960_RESUME_FAIL,
    WM_MF_RCT_CONFIG_TX_POWER_FAIL,
    WM_MF_AGE8960_CONFIG_PFER_FAIL,
    WM_MF_AGE8960_CONFIG_IQ_TUNNING_FAIL,
    WM_MF_AGE8960_CONFIG_EPSK_MOD_ACCURACY_FAIL,
    WM_MF_AGE8960_FETCH_EPSK_OOS_FAIL,
    WM_MF_AGE8960_FETCH_EPSK_SBS_FAIL,

    WM_MF_PT_BOOT_RESUME_FAIL,
    WM_MF_PT_CALIBRATION_NEW_FAIL,

    // query
    WM_MF_QUERY_RFTWOAPCDOOFFSET_SUCCESS,
    WM_MF_QUERY_RFTWOAPCDOOFFSET_FAILED,

    // file
    WM_MF_CFG_READ_FAIL,
    WM_MF_CFG_CHECK_PCL_FAIL,
    WM_MF_INI_READ_FAIL,
    WF_MF_INI_RX_PATH_LOSS_FAIL,
    WM_MF_LOG_OPEN_FAIL,
    WM_MF_LOG_WRITE_FAIL,

    // baseband
    WM_MF_BB_REG_READ_FAIL,
    WM_MF_BB_REG_WRITE_FAIL,
    WM_MF_BB_REG_SET_FAIL,

    // messages for META facotry RF calibration
    // RF common
    WM_MF_RF_STOP_FAIL,
    WM_MF_RF_SELECT_BAND_FAIL,

    // AFC
    WM_MF_RF_AFC_BEGIN,
    WM_MF_AFC_NOT_CHECK,
    WM_MF_RF_AFC_CONTROL_CNF,
    WM_MF_RF_AFC_CONTROL_FAIL,
    WM_MF_RF_AFC_GET_AFCDAC_FAIL,
    WM_MF_RF_AFC_CHECK_FAIL,
    WM_MF_RF_AFC_SET_CONT_SINE_WAVE_FLAG_FAIL,
    WM_MF_RF_SET_AFC_DAC_FAIL,
    WM_MF_RF_SET_AFC_DAC_CNF_FAIL,
    WM_MF_RF_AFC_WRITE_CAL_RESULT_FAIL,
    WM_MF_RF_AFC_CALIBRATION_DONE,

    // crystal AFC
    WM_MF_RF_CRYSTAL_AFC_CAPID_BEGIN,
    WM_MF_RF_CRYSTAL_AFC_CAPID_CHECK_FAIL,
    WM_MF_RF_CRYSTAL_AFC_CAPID_DONE,
    WM_MF_RF_CRYSTAL_AFC_SELECT_BAND_FAIL,
    WM_MF_RF_CRYSTAL_AFC_CONTROL_START,
    WM_MF_RF_CRYSTAL_AFC_CONTROL_CNF,
    WM_MF_RF_CRYSTAL_AFC_CONTROL_FAIL,
    WM_MF_RF_CRYSTAL_AFC_TX_LEVEL_FAIL,
    WM_MF_RF_CRYSTAL_AFC_PRECHECK_FAIL,
    WM_MF_RF_CRYSTAL_AFC_CHECK_FAIL,
    WM_MF_RF_SET_CRYSTAL_AFC_DAC_FAIL,
    WM_MF_RF_SET_CRYSTAL_AFC_DAC_CNF_FAIL,
    WM_MF_RF_CRYSTAL_AFC_SET_CAPID_FAIL,
    WM_MF_RF_CRYSTAL_AFC_WRITE_CAL_RESULT_FAIL,
    WM_MF_RF_CRYSTAL_AFC_ALL_FREQ_ERR_POSITIVE_FAIL,
    WM_MF_RF_CRYSTAL_AFC_ALL_FREQ_ERR_NEGATIVE_FAIL,
    WM_MF_RF_CRYSTAL_AFC_TRX_OFFSET_BEGIN,
    WM_MF_RF_CRYSTAL_AFC_TRX_OFFSET_CALIBRATION_DONE,
    WM_MF_RF_CRYSTAL_AFC_CALIBRATION_DONE,


    // RX path loss
    WM_MF_RF_PM_BEGIN,
    WM_MF_RF_PM_INI_FAIL,
    WM_MF_RF_PM_SUPPORT_FAIL,
    WM_MF_RF_SELECTBAND_CNF_FAIL,
    WM_MF_RF_SELECTBAND_CNF_SUCCESS,
    WM_MF_RF_PM_CNF,
    WM_MF_RF_PM_FAIL,
    WM_MF_RF_PM_SELECT_BAND_FAIL,
    WM_MF_RF_PM_CHECK_FAIL,
    WM_MF_RF_PM_WRITE_CAL_RESULT_FAIL,
    WM_MF_RF_PM_CALIBRATION_DONE,

    // IP2
    WM_MF_RF_IP2_BEGIN,
    WM_MF_RF_IP2_SET_MAG_FAIL,
    WM_MF_RF_IP2_SET_POL_FAIL,
    WM_MF_RF_IP2_SET_AMCALMODE_FAIL,
    WM_MF_RF_IP2_SET_CW2_FAIL,
    WM_MF_RF_IP2_SET_CW7_FAIL,
    WM_MF_RF_IP2_SET_BCCODE_FAIL,
    WM_MF_RF_IP2_SET_MT6139_COEF_FAIL,
    WM_MF_RF_IP2_GET_ACODE_FAIL,
    WM_MF_RF_IP2_GET_CW7_FAIL,
    WM_MF_RF_IP2_GET_BCCODE_FAIL,
    WM_MF_RF_IP2_PM_FAIL,
    WM_MF_RF_IP2_FAIL,
    WM_MF_RF_IP2_EVALUATE_CX_FAIL,
    WM_MF_RF_IP2_CHECK_FAIL,
    WM_MF_RF_IP2_WRITE_CAL_RESULT_FAIL,
    WM_MF_RF_IP2_CALIBRATION_DONE,

    // TX FB DAC
    WM_MF_RF_TX_FB_DAC_BEGIN,
    WM_MF_RF_TX_FB_DAC_INI_FAIL,
    WM_MF_RF_TX_FB_DAC_CHECK_FAIL,
    WM_MF_RF_TX_FB_DAC_CALIBRATION_DONE,

    // TX PCL
    WM_MF_RF_TX_LEVEL_BEGIN,
    WM_MF_RF_TX_LEVEL_CNF,
    WM_MF_RF_TX_LEVEL_INI_FAIL,
    WM_MF_RF_QUERY_ITC_PCL_FAIL,
    WM_MF_RF_TX_LEVEL_FAIL,
    WM_MF_RF_TX_LEVEL_EVALDAC_FAIL,
    WM_MF_RF_TX_LEVEL_CHECK_FAIL,
    WM_MF_RF_MAX_APC_DAC_OUT_OF_RANGE_FAIL,
    WM_MF_SET_APC_DAC_FAIL,
    WM_MF_SET_APC_DC_OFFSET_FAIL,
    WM_MF_RF_TX_LEVEL_WRITE_CAL_RESULT_FAIL,
    WM_MF_RF_TX_LEVEL_CALIBRATION_DONE,
    WM_MF_RF_TX_LEVEL_CALIBRATION_DONE_NO_CHECK,
    WM_MF_RF_A60111A_ENTER_FACTORY_MODE_FAIL,
    WM_MF_RF_A60111A_READ_REF_TEMP_FAIL,

    // TX slope skew
    WM_MF_RF_TX_SLOW_SKEW_BEGIN,
    WM_MF_RF_TX_SLOW_SKEW_INI_FAIL,
    WM_MF_RF_TX_SLOW_SKEW_CHECK_FAIL,
    WM_MF_RF_TX_SLOW_SKEW_CALIBRATION_DONE,

    // Trim, offset IQ
    WM_MF_RF_GET_BB_TX_CFG_FAIL,
    WM_MF_RF_SET_BB_TX_CFG_FAIL,
    WM_MF_RF_TX_GAIN_AUTO_CAL_FAIL,
    WM_MF_RF_TX_IQ_BEGIN,
    WM_MF_RF_TX_IQ_FAIL,
    WM_MF_RF_TX_IQ_CHECK_FAIL,
    WM_MF_RF_TX_IQ_CALIBRATION_DONE,

    // runtime setting
    WM_MF_RF_SET_AD6546TX_COEF_FAIL,

    // NVRAM
    WM_MF_NVRAM_AFC_READ_FAIL,
    WM_MF_NVRAM_AFC_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_AFCDATA_LID_VERNO_FAIL,
    WM_MF_NVRAM_CRYSTAL_AFC_DATA_READ_FAIL,
    WM_MF_NVRAM_CRYSTAL_AFC_DATA_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_CRYSTAL_AFCDATA_LID_VERNO_FAIL,
    WM_MF_NVRAM_CRYSTAL_AFC_CAPID_READ_FAIL,
    WM_MF_NVRAM_CRYSTAL_AFC_CAPID_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_CRYSTAL_CAPDATA_LID_VERNO_FAIL,
    WM_MF_NVRAM_PATH_LOSS_WRITE_CNF,
    WM_MF_NVRAM_PATH_LOSS_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_AGCPATHLOSS_LID_VERNO_FAIL,
    WM_MF_NVRAM_IP2_READ_FAIL,
    WM_MF_NVRAM_IP2_READ_CNF,
    WM_MF_NVRAM_IP2_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_RFSPECIALCOEF_LID_VERNO_FAIL,
    WM_MF_NVRAM_IP2_WRITE_CNF,
    WM_MF_NVRAM_AD6546_COEF_READ_FAIL,
    WM_MF_NVRAM_AD6546_COEF_WRITE_FAIL,
    WM_MF_NVRAM_LEVEL_RAMP_WRITE_CNF,
    WM_MF_NVRAM_LEVEL_RAMP_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_RAMPTABLE_xxx_LID_VERNO_FAIL,
    WM_MF_NVRAM_EF_L1_EPSK_RAMPTABLE_xxx_LID_VERNO_FAIL,
    WM_MF_NVRAM_LEVEL_RAMP_READ_CNF,
    WM_MF_NVRAM_LEVEL_RAMP_READ_FAIL,
    WM_MF_NVRAM_TXIQ_READ_FAIL,
    WM_MF_NVRAM_TXIQ_WRITE_FAIL,
    WM_MF_NVRAM_EF_L1_TXIQ_LID_VERNO_FAIL,
    WM_MF_NVRAM_ADC_READ_FAIL,
    WM_MF_NVRAM_ADC_WRITE_FAIL,
    WM_MF_NVRAM_EF_ADC_LID_VERNO_FAIL,
    WM_MF_NVRAM_WIFI_APC_READ_FAIL,
    WM_MF_NVRAM_WIFI_APC_WRITE_FAIL,
    WM_MF_NVRAM_WIFI_ALC_READ_FAIL,
    WM_MF_NVRAM_WIFI_ALC_WRITE_FAIL,
    WM_MF_NVRAM_WIFI_TX_DC_OFFSET_READ_FAIL,
    WM_MF_NVRAM_WIFI_TX_DC_OFFSET_WRITE_FAIL,
    WM_MF_NVRAM_EF_WNDRV_DAC_DC_OFFSET_LID_VERNO_FAIL,
    WM_MF_NVRAM_EF_WNDRV_TX_POWER_xxx_LID_VERNO_FAIL,
    WM_MF_NVRAM_EF_WNDRV_TX_ALC_POWER_LID_VERNO_FAIL,
    WM_MF_NVRAM_EF_WNDRV_ALC_SLOPE_LID_VERNO_FAIL,
    WM_MF_NVRAM_BT_INFO_READ_FAIL,
    WM_MF_NVRAM_BT_INFO_WRITE_FAIL,
    WM_MF_NVRAM_EF_BTRADIO_MT6601_LID_VERNO_FAIL,
    WM_MF_NVRAM_CV_READ_FAIL,
    WM_MF_NVRAM_CV_WRITE_FAIL,
    WM_MF_NVRAM_REF_TEMP_READ_FAIL,
    WM_MF_NVRAM_REF_TEMP_WRITE_FAIL,

    // RF runtime setting
    WM_MF_SET_RAMPAPCLEVEL_FAIL,
    WM_MF_SET_RAMPAPCLEVEL_CNF,
    WM_MF_CA_SUCCESS,
    WM_MF_CA_FAIL,
    WM_MF_CA_TERM_BY_USER,


    // ADC calibration
    WM_MF_ADC_BEGIN,
    WM_MF_ADC_DCS_INIT_FAIL,
    WM_MF_ADC_DCS_SET_VOLTAGE_CURRENT_FAIL,
    WM_MF_ADC_DCS_MEASURE_VOLTAGE_FAIL,
    WM_MF_ADC_DCS_CLOSE_FAIL,
    WM_MF_ADC_SUCCESS,
    WM_MF_ADC_FAIL,
    WM_MF_ADC_TERM_BY_USER,
    WM_MF_PT_ADC_CALIBRATION_NEW_FAIL,


    WM_MF_ADC_MEASURE_FAIL,
    WM_MF_ADC_MEASURE_CNF_FAIL,
    WM_MF_ADC_CHECK_BATTERY_VOLTAGE_DIFFERENCE_FAIL,
    WM_MF_ADC_CHECK_CURRENT_DIFFERENCE_FAIL,
    WM_MF_ADC_EVALUATE_SLOPE_OFFSET_FAIL,

    WM_MF_ADC_CHECK_SLOPE_OFFSET_FAIL,
    WM_MF_ADC_WRITE_CAL_RESULT_FAIL,
    WM_MF_ADC_CHECK_SLOPE_OFFSET_PASS,
    WM_MF_ADC_CALIBRATION_DONE,

    // CV calibration
    WM_MF_CV_BEGIN,
    WM_MF_CV_CHECK_FAIL,
    WM_MF_CV_CALIBRATION_DONE,

    // WiFi TX power calibration
    WM_MF_WIFI_TX_RATE_802_11B_FAIL,
    WM_MF_WIFI_TX_RATE_802_11AG_FAIL,
    WM_MF_WIFI_CHANNEL_802_11B_FAIL,
    WM_MF_WIFI_CHANNEL_802_11AG_FAIL,
    WM_MF_WIFI_CHANNEL_INDEX_NOT_FOUND_FAIL,
    WM_MF_WIFI_TX_POWER_BEGIN,
    WM_MF_WIFI_CPT_FAIL,
    WM_MF_WIFI_CPT_STOP_FAIL,
    WM_MF_WIFI_INIT_FAIL,
    WM_MF_WIFI_TERMINATE_FAIL,
    WM_MF_WIFI_CONN_OPEN_FAIL,
    WM_MF_WIFI_CONN_CLOSE_FAIL,
    WM_MF_WIFI_CONN_UPDATE_CALDATA_FAIL,
    WM_MF_WIFI_SET_DEFAULT_FAIL,
    WM_MF_WIFI_SET_PACKET_LEN_FAIL,
    WM_MF_WIFI_SET_TRIGGER_STYLE_FAIL,
    WM_MF_WIFI_APPLY_CHANGE_FAIL,
    WM_MF_WIFI_SET_POWER_RANGE_FAIL,
    WM_MF_WIFI_SET_CENTRAL_FREQ_FAIL,
    WM_MF_WIFI_DATA_CAPTURE_FAIL,
    WM_MF_WIFI_ANALYZE_POWER_FAIL,
    WM_MF_WIFI_READ_POWER_FAIL,
    WM_MF_WIFI_TX_POWER_CHECK_FAIL,
    WM_MF_WIFI_TX_POWER_CALIBRATION_DONE,
    // WiFi TX DC offset calibration
    WM_MF_WIFI_TX_DC_OFFSET_BEGIN,
    WM_MF_WIFI_TX_DC_OFFSET_FAIL,
    WM_MF_WIFI_TX_DC_OFFSET_CALIBRATION_DONE,

    // BT
    WM_MF_BTT_INIT_FAIL,
    WM_MF_BTT_CLOSE_FAIL,
    WM_MF_BTT_CONFIG_SLAVE_PARAMETER_FAIL,
    WM_MF_BTT_CONFIG_DOWNLINK_POWER_FAIL,
    WM_MF_BTT_CONFIG_BD_ADDRESS_FAIL,
    WM_MF_BTT_CONFIG_INQUIRY_FAIL,
    WM_MF_BTT_CONFIG_SCAN_FAIL,
    WM_MF_BTT_INQUIRY_FAIL,
    WM_MF_BTT_CONNECT_TEST_FAIL,
    WM_MF_BTT_RELEASE_FAIL,
    WM_MF_BTT_QUERY_STATE_FAIL,
    WM_MF_BTT_CONFIG_MOD_FAIL,
    WM_MF_BTT_READ_FREQ_ACCURACY,
    WM_MF_BT_CRYSTAL_CAPID_BEGIN,
    WM_MF_BT_CRYSTAL_CAPID_WRITE_CAL_RESULT_FAIL,
    WM_MF_BT_CRYSTAL_CAPID_CHECK_FAIL,
    WM_MF_BT_CRYSTAL_CAPID_CALIBRATION_DONE,
    WM_MF_BT_ENABLE_PCM_CLOCK_SYNC_SIGNAL_FAIL,
    WM_MF_BT_START_CALIBRATE_CRYSTAL_CLOCK_FAIL,
    WM_MF_BT_READ_CRYSTAL_CLOCK_RESULT_FAIL,
    WM_MF_BT_SET_CRYSTAL_CAPID_FAIL,
    WM_MF_BT_ENTER_TEST_MODE_FAIL,
    WM_MF_BT_INQUIRY_ENABLE_FAIL,

    WM_META_DLL_LID_INVALID,
    WM_MF_CALIBRATION_TIMER_TIME_OUT,
    // messages for iMelody
    WM_IMELODY_DOWNLOAD,
    WM_IMELODY_PLAY_CNF,
    WM_IMELODY_PLAY_OVER,
    WM_IMELODY_DEL,
    WM_IMELODY_INFO,
    WM_IMELODY_PLAY_FAIL,
    WM_IMELODY_STOP_CNF,
    WM_IMELODY_STOP_FAIL,
    // reconnect
    WM_MF_RECONNECT_WITH_TARGET_SUCCESS

    //FM


//         WM_META_MSG_END = WM_META_DLL_ERROR_UNDEFINE_ERROR
} ErrorMsg;
#endif
