#ifndef  _NVRAM_VER_H_
#define  _NVRAM_VER_H_

#define  NVRAM_EF_L1_AGCPATHLOSS_LID_VERNO                   2
#define  NVRAM_EF_L1_RAMPTABLE_GSM850_LID_VERNO              3
#define  NVRAM_EF_L1_RAMPTABLE_GSM900_LID_VERNO              3
#define  NVRAM_EF_L1_RAMPTABLE_DCS1800_LID_VERNO             3
#define  NVRAM_EF_L1_RAMPTABLE_PCS1900_LID_VERNO             3
#define  NVRAM_EF_L1_EPSK_RAMPTABLE_GSM850_LID_VERNO         3
#define  NVRAM_EF_L1_EPSK_RAMPTABLE_GSM900_LID_VERNO         3
#define  NVRAM_EF_L1_EPSK_RAMPTABLE_DCS1800_LID_VERNO        3
#define  NVRAM_EF_L1_EPSK_RAMPTABLE_PCS1900_LID_VERNO        3
#define  NVRAM_EF_L1_EPSK_INTERSLOT_RAMP_GSM850_LID_VERNO    2
#define  NVRAM_EF_L1_EPSK_INTERSLOT_RAMP_GSM900_LID_VERNO    2
#define  NVRAM_EF_L1_EPSK_INTERSLOT_RAMP_DCS1800_LID_VERNO   2
#define  NVRAM_EF_L1_EPSK_INTERSLOT_RAMP_PCS1900_LID_VERNO   2
#define  NVRAM_EF_L1_AFCDATA_LID_VERNO                       2
#define  NVRAM_EF_L1_TXIQ_LID_VERNO                          4
#define  NVRAM_EF_L1_RFSPECIALCOEF_LID_VERNO                 5
#define  NVRAM_EF_L1_INTERSLOT_RAMP_GSM850_LID_VERNO         2
#define  NVRAM_EF_L1_INTERSLOT_RAMP_GSM900_LID_VERNO         2
#define  NVRAM_EF_L1_INTERSLOT_RAMP_DCS1800_LID_VERNO        2
#define  NVRAM_EF_L1_INTERSLOT_RAMP_PCS1900_LID_VERNO        2
#define  NVRAM_EF_L1_CRYSTAL_AFCDATA_LID_VERNO               2
#define  NVRAM_EF_L1_CRYSTAL_CAPDATA_LID_VERNO               2
#define  NVRAM_EF_WNDRV_MAC_ADDRESS_LID_VERNO                0
#define  NVRAM_EF_WNDRV_TX_POWER_2400M_LID_VERNO             0
#define  NVRAM_EF_WNDRV_TX_POWER_5000M_LID_VERNO             0
#define  NVRAM_EF_WNDRV_DAC_DC_OFFSET_LID_VERNO              0
#define  NVRAM_EF_WNDRV_TX_ALC_POWER_LID_VERNO               0
#define  NVRAM_EF_WNDRV_ALC_SLOPE_LID_VERNO                  0
#define  NVRAM_EF_BTRADIO_MT6601_LID_VERNO                   0
#define  NVRAM_EF_ADC_LID_VERNO                              0
#define  NVRAM_EF_BARCODE_NUM_LID_VERNO                      0
#define  NVRAM_EF_IMEI_IMEISV_LID_VERNO                      0
#define  NVRAM_EF_AUDIO_PARAM_LID_VERNO                      6 // W0809


#define  NVRAM_EF_AUDIO_BESLOUDNESS_LID_VERNO                1

#endif
